version: '3.5'
volumes:
  data:

services:
  database:
    image: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=api-cidades
    volumes:
      - data:/var/lib/postgresql/data